// <auto-generated />
namespace AccBroker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddedFieldsUserCreateChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFieldsUserCreateChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201604160538016_Added Fields User Create Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
